events {}

http {
    upstream flask_app {
        server app:5000;
        server app:5000;
        server app:5000;
    }

    # Redirection HTTP → HTTPS
    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    # HTTPS
    server {
        listen 443 ssl;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        location / {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
        }
    }
}